/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (C) 2026 Interpretica Unipessoal Lda */
/** @file
 * @brief Frida TAPI
 *
 * Implementation of the Frida TAPI and of the scripts it generates.
 */

#define TE_LGR_USER "TAPI FRIDA"

#include "te_config.h"

#include <arpa/inet.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

#include "logger_api.h"
#include "tapi_cfg_base.h"
#include "tapi_file.h"
#include "te_alloc.h"
#include "te_kvpair.h"
#include "te_sockaddr.h"
#include "te_str.h"
#include "te_string.h"
#include "te_vector.h"

#include "tapi_devtool_run.h"
#include "tapi_frida.h"

struct tapi_frida_app {
    /** Frida job. */
    tapi_devtool_run run;
};

const tapi_frida_opt tapi_frida_default_opt = {
    .frida       = NULL,
    .device      = NULL,
    .target_name = NULL,
    .target_pid  = TAPI_JOB_OPT_OMIT_UINT,
    .spawn       = NULL,
    .script_path = NULL,
    .no_pause    = true,
    .runtime     = NULL,
};

static const tapi_job_opt_bind frida_binds[] = TAPI_JOB_OPT_SET(
    /* Non-interactive: the test drives, nobody types. */
    TAPI_JOB_OPT_DUMMY("-q"),
    TAPI_JOB_OPT_STRING("-H", false, tapi_frida_opt, device),
    TAPI_JOB_OPT_STRING("-n", false, tapi_frida_opt, target_name),
    TAPI_JOB_OPT_UINT_OMITTABLE("-p", false, NULL, tapi_frida_opt,
                                target_pid),
    TAPI_JOB_OPT_STRING("-l", false, tapi_frida_opt, script_path),
    TAPI_JOB_OPT_BOOL("--no-pause", tapi_frida_opt, no_pause),
    TAPI_JOB_OPT_STRING("--runtime=", true, tapi_frida_opt, runtime),
    /* -f and the program arguments must come last. */
    TAPI_JOB_OPT_STRING("-f", false, tapi_frida_opt, spawn),
    TAPI_JOB_OPT_ARRAY_PTR(tapi_frida_opt, n_spawn_args, spawn_args,
        TAPI_JOB_OPT_CONTENT(TAPI_JOB_OPT_STRING, NULL, false))
);

/** A plain argument vector, for the odd one-off command. */
typedef struct frida_args_opt {
    size_t n_args;
    const char **args;
} frida_args_opt;

static const tapi_job_opt_bind frida_args_binds[] = TAPI_JOB_OPT_SET(
    TAPI_JOB_OPT_ARRAY_PTR(frida_args_opt, n_args, args,
        TAPI_JOB_OPT_CONTENT(TAPI_JOB_OPT_STRING, NULL, false))
);

/* See description in tapi_frida.h */
te_errno
tapi_frida_check_available(tapi_job_factory_t *factory, int timeout_ms)
{
    const char *args[] = { "--version" };
    frida_args_opt opt = { .n_args = TE_ARRAY_LEN(args), .args = args };
    tapi_devtool_output output;
    tapi_devtool_run run = TAPI_DEVTOOL_RUN_INIT;
    te_errno rc;

    rc = tapi_devtool_run_init(&run, factory, "frida", "frida",
                               frida_args_binds, &opt, NULL);
    if (rc != 0)
        return TE_RC(TE_TAPI, TE_ENOENT);

    rc = tapi_devtool_run_start(&run);
    if (rc == 0)
        rc = tapi_devtool_run_wait(&run, timeout_ms);

    if (rc == 0)
    {
        tapi_devtool_run_get_output(&run, &output);
        if (output.status.type == TAPI_JOB_STATUS_EXITED &&
            output.status.value == 0)
        {
            RING("Frida on the agent: %s", output.out);
        }
        else
        {
            rc = TE_RC(TE_TAPI, TE_ENOENT);
        }
    }
    else
    {
        rc = TE_RC(TE_TAPI, TE_ENOENT);
    }

    tapi_devtool_run_fini(&run);

    if (rc != 0)
        RING("Frida is not available on the agent");

    return rc;
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_script_put(const char *ta, const char *script, te_string *path)
{
    char *tmp_dir;
    te_errno rc;

    tmp_dir = tapi_cfg_base_get_ta_dir(ta, TAPI_CFG_BASE_TA_DIR_TMP);
    if (tmp_dir == NULL)
    {
        ERROR("Failed to get the temporary directory of TA %s", ta);
        return TE_RC(TE_TAPI, TE_EFAIL);
    }

    tapi_file_make_custom_pathname(path, tmp_dir, ".js");
    free(tmp_dir);

    rc = tapi_file_create_ta(ta, path->ptr, "%s", script);
    if (rc != 0)
        ERROR("Failed to put the Frida script on TA %s: %r", ta, rc);

    return rc;
}

/** The preamble every generated script shares. */
static void
frida_script_header(te_string *script, const char *what)
{
    te_string_append(script,
        "/* Generated by tapi_frida: %s.\n"
        " * Test instrumentation. It is not part of any product.\n"
        " */\n", what);
}

/* See description in tapi_frida.h */
void
tapi_frida_script_trace_calls(const char *const *functions, te_string *script)
{
    size_t i;

    frida_script_header(script, "report calls to a list of functions");

    te_string_append(script, "(function () {\n    var names = [");
    for (i = 0; functions[i] != NULL; i++)
        te_string_append(script, "%s'%s'", i == 0 ? "" : ", ", functions[i]);
    te_string_append(script, "];\n");

    te_string_append(script,
        "    names.forEach(function (name) {\n"
        "        var addr = Module.findExportByName(null, name);\n"
        "        if (addr === null)\n"
        "            return;\n"
        "        Interceptor.attach(addr, {\n"
        "            onEnter: function () {\n"
        "                var site = '?';\n"
        "                try {\n"
        "                    var frames = Thread.backtrace(this.context,\n"
        "                        Backtracer.ACCURATE);\n"
        "                    if (frames.length > 0)\n"
        "                        site = DebugSymbol.fromAddress(frames[0])\n"
        "                                          .toString();\n"
        "                } catch (e) {\n"
        "                }\n"
        "                console.log('%scall|' + name + '|from=' + site);\n"
        "            }\n"
        "        });\n"
        "    });\n"
        "})();\n", TAPI_FRIDA_EVENT_PREFIX);
}

/* See description in tapi_frida.h */
void
tapi_frida_script_fail_call(const char *function, unsigned int nth,
                            long retval, int err, te_string *script)
{
    frida_script_header(script, "make one call fail");

    te_string_append(script,
        "(function () {\n"
        "    var name = '%s';\n"
        "    var nth = %u;\n"
        "    var errnum = %d;\n"
        "    var seen = 0;\n"
        "    var addr = Module.findExportByName(null, name);\n"
        "    if (addr === null) {\n"
        "        console.log('%serror|' + name + '|not found');\n"
        "        return;\n"
        "    }\n"
        "    Interceptor.attach(addr, {\n"
        "        onLeave: function (retval) {\n"
        "            seen++;\n"
        "            if (seen !== nth)\n"
        "                return;\n"
        "            retval.replace(ptr(%ld));\n"
        "            if (errnum !== 0) {\n"
        "                var loc = Module.findExportByName(null,\n"
        "                    '__errno_location');\n"
        "                if (loc !== null) {\n"
        "                    new NativeFunction(loc, 'pointer', [])()\n"
        "                        .writeInt(errnum);\n"
        "                }\n"
        "            }\n"
        "            console.log('%sfail|' + name + '|call=' + seen);\n"
        "        }\n"
        "    });\n"
        "})();\n",
        function, nth, err, TAPI_FRIDA_EVENT_PREFIX, retval,
        TAPI_FRIDA_EVENT_PREFIX);
}

/* See description in tapi_frida.h */
void
tapi_frida_script_trace_open(te_string *script)
{
    frida_script_header(script, "report every file the target opens");

    te_string_append(script,
        "(function () {\n"
        "    ['open', 'open64', 'openat', 'fopen'].forEach(function (name) {\n"
        "        var addr = Module.findExportByName(null, name);\n"
        "        if (addr === null)\n"
        "            return;\n"
        "        var which = (name === 'openat') ? 1 : 0;\n"
        "        Interceptor.attach(addr, {\n"
        "            onEnter: function (args) {\n"
        "                var path = '?';\n"
        "                try {\n"
        "                    path = args[which].readUtf8String();\n"
        "                } catch (e) {\n"
        "                }\n"
        "                console.log('%sopen|' + path + '|via=' + name);\n"
        "            }\n"
        "        });\n"
        "    });\n"
        "})();\n", TAPI_FRIDA_EVENT_PREFIX);
}

/* See description in tapi_frida.h */
void
tapi_frida_script_trace_connect(te_string *script)
{
    frida_script_header(script, "report every address the target connects to");

    /*
     * The sockaddr is read the way Linux lays it out: the family in the
     * first two bytes, the port right after it in network order, and
     * the address at 4 for IPv4 and at 8 for IPv6.
     */
    te_string_append(script,
        "(function () {\n"
        "    var addr = Module.findExportByName(null, 'connect');\n"
        "    if (addr === null)\n"
        "        return;\n"
        "    Interceptor.attach(addr, {\n"
        "        onEnter: function (args) {\n"
        "            var sa = args[1];\n"
        "            var text = null;\n"
        "            var port = 0;\n"
        "            try {\n"
        "                var family = sa.readU16();\n"
        "                port = (sa.add(2).readU8() << 8) |\n"
        "                       sa.add(3).readU8();\n"
        "                if (family === 2) {\n"
        "                    var quad = [];\n"
        "                    for (var i = 0; i < 4; i++)\n"
        "                        quad.push(sa.add(4 + i).readU8());\n"
        "                    text = quad.join('.');\n"
        "                } else if (family === 10) {\n"
        "                    var parts = [];\n"
        "                    for (var j = 0; j < 8; j++) {\n"
        "                        var hi = sa.add(8 + j * 2).readU8();\n"
        "                        var lo = sa.add(9 + j * 2).readU8();\n"
        "                        parts.push(((hi << 8) | lo).toString(16));\n"
        "                    }\n"
        "                    text = parts.join(':');\n"
        "                }\n"
        "            } catch (e) {\n"
        "            }\n"
        "            if (text !== null)\n"
        "                console.log('%sconnect|' + text + '|port=' + port);\n"
        "        }\n"
        "    });\n"
        "})();\n", TAPI_FRIDA_EVENT_PREFIX);
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_create(tapi_job_factory_t *factory, const tapi_frida_opt *opt,
                  tapi_frida_app **app)
{
    tapi_frida_app *result;
    te_errno rc;

    if (opt->script_path == NULL)
    {
        ERROR("Frida needs a script to run");
        return TE_RC(TE_TAPI, TE_EINVAL);
    }

    if (opt->target_name == NULL && opt->spawn == NULL &&
        opt->target_pid == TAPI_JOB_OPT_OMIT_UINT)
    {
        ERROR("Frida needs a target: a name, a pid or a program to spawn");
        return TE_RC(TE_TAPI, TE_EINVAL);
    }

    result = TE_ALLOC(sizeof(*result));
    result->run = (tapi_devtool_run)TAPI_DEVTOOL_RUN_INIT;

    rc = tapi_devtool_run_init(&result->run, factory, "frida",
                               opt->frida != NULL ? opt->frida : "frida",
                               frida_binds, opt, opt->workdir);
    if (rc != 0)
    {
        free(result);
        return rc;
    }

    *app = result;

    return 0;
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_start(tapi_frida_app *app)
{
    return tapi_devtool_run_start(&app->run);
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_wait(tapi_frida_app *app, int timeout_ms)
{
    return tapi_devtool_run_wait(&app->run, timeout_ms);
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_stop(tapi_frida_app *app)
{
    te_errno rc;

    rc = tapi_devtool_run_stop(&app->run);
    if (rc != 0)
        return rc;

    /*
     * Frida is expected to be told to stop, so its exit status is not
     * checked; what matters is everything it printed before that.
     */
    return tapi_devtool_run_wait(&app->run, TAPI_DEVTOOL_TERM_TIMEOUT_MS * 5);
}

/* See description in tapi_frida.h */
void
tapi_frida_get_output(const tapi_frida_app *app, tapi_devtool_output *output)
{
    tapi_devtool_run_get_output(&app->run, output);
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_destroy(tapi_frida_app *app)
{
    te_errno rc;

    if (app == NULL)
        return 0;

    rc = tapi_devtool_run_fini(&app->run);
    free(app);

    return rc;
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_events(const tapi_frida_app *app, te_vec *events)
{
    size_t prefix_len = strlen(TAPI_FRIDA_EVENT_PREFIX);
    tapi_devtool_output output;
    char *text;
    char *line;
    char *saveptr = NULL;

    *events = (te_vec)TE_VEC_INIT(tapi_frida_event);

    tapi_frida_get_output(app, &output);
    text = TE_STRDUP(output.out);

    for (line = strtok_r(text, "\n", &saveptr);
         line != NULL;
         line = strtok_r(NULL, "\n", &saveptr))
    {
        tapi_frida_event event;
        char *kind;
        char *name;
        char *detail;
        char *sep;

        if (strncmp(line, TAPI_FRIDA_EVENT_PREFIX, prefix_len) != 0)
            continue;

        kind = line + prefix_len;
        sep = strchr(kind, '|');
        if (sep == NULL)
            continue;
        *sep = '\0';

        name = sep + 1;
        sep = strchr(name, '|');
        if (sep != NULL)
        {
            *sep = '\0';
            detail = sep + 1;
        }
        else
        {
            detail = (char *)"";
        }

        event.kind = TE_STRDUP(kind);
        event.name = TE_STRDUP(name);
        event.detail = TE_STRDUP(detail);
        TE_VEC_APPEND(events, event);
    }

    free(text);

    return 0;
}

/* See description in tapi_frida.h */
void
tapi_frida_events_free(te_vec *events)
{
    tapi_frida_event *event;

    TE_VEC_FOREACH(events, event)
    {
        free(event->kind);
        free(event->name);
        free(event->detail);
    }

    te_vec_free(events);
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_check_banned_calls(const tapi_frida_app *app,
                              tapi_cybersec_report *report)
{
    const tapi_frida_event *event;
    te_kvpair_h seen;
    te_vec events;
    te_errno rc;

    te_kvpair_init(&seen);

    rc = tapi_frida_events(app, &events);
    if (rc != 0)
    {
        te_kvpair_fini(&seen);
        return rc;
    }

    TE_VEC_FOREACH(&events, event)
    {
        te_string key = TE_STRING_INIT;

        if (strcmp(event->kind, "call") != 0)
            continue;

        /* One finding per (function, call site). */
        te_string_append(&key, "%s|%s", event->name, event->detail);
        if (te_kvpairs_get_nth(&seen, key.ptr, 0) == NULL)
        {
            te_kvpair_push(&seen, key.ptr, "1");
            tapi_cybersec_report_add(report, TAPI_CYBERSEC_SEV_HIGH,
                                     "runtime.banned-call", event->name,
                                     "called while the test was running, %s",
                                     event->detail[0] != '\0' ?
                                         event->detail : "call site unknown");
        }
        te_string_free(&key);
    }

    tapi_frida_events_free(&events);
    te_kvpair_fini(&seen);

    return 0;
}

/** Turn a traced connect event into an address. */
static bool
frida_event_to_addr(const tapi_frida_event *event,
                    struct sockaddr_storage *addr)
{
    const char *port_text = strstr(event->detail, "port=");
    unsigned int port = 0;

    if (port_text == NULL || te_strtoui(port_text + 5, 10, &port) != 0)
        return false;

    memset(addr, 0, sizeof(*addr));

    if (strchr(event->name, ':') == NULL)
    {
        struct sockaddr_in *sin = (struct sockaddr_in *)addr;

        if (inet_pton(AF_INET, event->name, &sin->sin_addr) != 1)
            return false;

        sin->sin_family = AF_INET;
        sin->sin_port = htons((uint16_t)port);
    }
    else
    {
        struct sockaddr_in6 *sin6 = (struct sockaddr_in6 *)addr;

        if (inet_pton(AF_INET6, event->name, &sin6->sin6_addr) != 1)
            return false;

        sin6->sin6_family = AF_INET6;
        sin6->sin6_port = htons((uint16_t)port);
    }

    return true;
}

/* See description in tapi_frida.h */
te_errno
tapi_frida_check_egress(const tapi_frida_app *app,
                        const tapi_egress_policy *policy,
                        tapi_cybersec_report *report)
{
    const tapi_frida_event *event;
    te_kvpair_h seen;
    te_vec events;
    te_errno rc;

    te_kvpair_init(&seen);

    rc = tapi_frida_events(app, &events);
    if (rc != 0)
    {
        te_kvpair_fini(&seen);
        return rc;
    }

    TE_VEC_FOREACH(&events, event)
    {
        struct sockaddr_storage addr;
        te_string subject = TE_STRING_INIT;

        if (strcmp(event->kind, "connect") != 0)
            continue;

        if (!frida_event_to_addr(event, &addr))
        {
            WARN("Cannot read an address out of '%s %s'", event->name,
                 event->detail);
            continue;
        }

        /*
         * connect() says nothing about the transport, so a destination
         * is only reported when no rule of either protocol allows it.
         */
        if (tapi_egress_policy_allows(policy, IPPROTO_TCP, SA(&addr)) ||
            tapi_egress_policy_allows(policy, IPPROTO_UDP, SA(&addr)))
            continue;

        te_string_append(&subject, "%s:%u", event->name,
                         ntohs(te_sockaddr_get_port(SA(&addr))));

        if (te_kvpairs_get_nth(&seen, subject.ptr, 0) == NULL)
        {
            te_kvpair_push(&seen, subject.ptr, "1");
            tapi_cybersec_report_add(report, TAPI_CYBERSEC_SEV_HIGH,
                                     "runtime.unexpected-egress",
                                     subject.ptr,
                                     "the traced process connected there and "
                                     "no rule allows it");
        }

        te_string_free(&subject);
    }

    tapi_frida_events_free(&events);
    te_kvpair_fini(&seen);

    return 0;
}
